/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ABtn {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface TestWebComp {
    }
}
declare global {
    interface HTMLABtnElement extends Components.ABtn, HTMLStencilElement {
    }
    var HTMLABtnElement: {
        prototype: HTMLABtnElement;
        new (): HTMLABtnElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLTestWebCompElement extends Components.TestWebComp, HTMLStencilElement {
    }
    var HTMLTestWebCompElement: {
        prototype: HTMLTestWebCompElement;
        new (): HTMLTestWebCompElement;
    };
    interface HTMLElementTagNameMap {
        "a-btn": HTMLABtnElement;
        "my-component": HTMLMyComponentElement;
        "test-web-comp": HTMLTestWebCompElement;
    }
}
declare namespace LocalJSX {
    interface ABtn {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface TestWebComp {
    }
    interface IntrinsicElements {
        "a-btn": ABtn;
        "my-component": MyComponent;
        "test-web-comp": TestWebComp;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "a-btn": LocalJSX.ABtn & JSXBase.HTMLAttributes<HTMLABtnElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "test-web-comp": LocalJSX.TestWebComp & JSXBase.HTMLAttributes<HTMLTestWebCompElement>;
        }
    }
}
